//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Deluc_practic2.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class Napominanie
    {
        public int ID { get; set; }
        public int UserID { get; set; }
        public System.DateTime Date { get; set; }
        public string text { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    
        public virtual User User { get; set; }
    }
}
